### ISSUE TITLE
V站过来 大佬能出点教程吗?

### ISSUE THREAD

**Issue by vcan** [DeepWisdom/AutoDL#1]
据说比谷歌的AudoML都厉害，想知道怎么使用，来个教程吧。

**Comment by iiiyu** [comment]
0基础也想要教程可能是从数据准备到得到结果的那种step by step。可以下面选几个
行人识别、行人动作识别、人脸识别、声纹识别、音乐分类、口音分类、语言分类、情感分类、邮件分类、新闻分类、广告优化、推荐系统、搜索引擎、精准营销

当然如果不是面向0基础的话。忽略我。

**Comment by geekan** [comment]
@vcan @iiiyu 其实现在按照使用说明step by step就能跑了。但是就是要费点功夫。
我们正在package化，要等几天
