### ISSUE TITLE
Can it solve a time series classification ?

### ISSUE THREAD

**Issue by SutirthaChakraborty** [DeepWisdom/AutoDL#39]
Hi,
I am a new bie,
I want to predict Beat detection in a music signal. Will it be possible? Do you have a similar code for that?
Regards,
Suti

**Comment by better629** [comment]
Hi,
    The repo does't support time series job. We have TSC work inside company but it may not to release yet. Maybe you can refer to FB Prophet and you can transform the signal into series first.

Thank you!
